-- Phase 5 geography seed: real cities + districts only (no fake projects/prices)

insert into public.cities (
  slug, name_en, name_zh, name_th,
  seo_title_en, seo_title_zh, seo_title_th,
  seo_description_en, seo_description_zh, seo_description_th,
  summary_en, summary_zh, summary_th, sort_order
) values
(
  'bangkok', 'Bangkok', '曼谷', 'กรุงเทพมหานคร',
  'Bangkok Property | GoThailandHome',
  '曼谷房产 | GoThailandHome',
  'อสังหาริมทรัพย์กรุงเทพฯ | GoThailandHome',
  'Browse real Bangkok condominium projects and verified public sale and rent listings.',
  '浏览曼谷真实共管公寓项目与已核对的公开买卖/租赁挂牌。',
  'ดูโครงการคอนโดและประกาศขาย/เช่าจริงในกรุงเทพฯ',
  'Thailand’s capital market for condominiums, transport nodes, and urban rental demand.',
  '泰国首都市场，聚焦公寓、轨道交通节点与城市租赁需求。',
  'ตลาดเมืองหลวงสำหรับคอนโด จุดเชื่อมขนส่ง และความต้องการเช่าในเมือง',
  1
),
(
  'pattaya', 'Pattaya', '芭提雅', 'พัทยา',
  'Pattaya Property | GoThailandHome',
  '芭提雅房产 | GoThailandHome',
  'อสังหาริมทรัพย์พัทยา | GoThailandHome',
  'Discover Pattaya property pages for coastal projects and public listings as inventory is imported.',
  '探索芭提雅房产页面；项目与挂牌随真实导入逐步上线。',
  'สำรวจหน้าอสังหาฯ พัทยา โครงการและประกาศจะเพิ่มเมื่อมีการนำเข้าข้อมูลจริง',
  'Eastern seaboard city known for beachfront and condo living.',
  '东海岸城市，以海滨与公寓生活闻名。',
  'เมืองชายฝั่งภาคตะวันออก ที่รู้จักด้านคอนโดและไลฟ์สไตล์ชายหาด',
  2
),
(
  'phuket', 'Phuket', '普吉', 'ภูเก็ต',
  'Phuket Property | GoThailandHome',
  '普吉房产 | GoThailandHome',
  'อสังหาริมทรัพย์ภูเก็ต | GoThailandHome',
  'Phuket property hub for imported island projects and public sale/rent listings.',
  '普吉房产中心页；仅展示已导入的真实项目与公开挂牌。',
  'ศูนย์อสังหาฯ ภูเก็ตสำหรับโครงการและประกาศที่นำเข้าจากแหล่งจริง',
  'Island market spanning tourist coasts and local residential areas.',
  '海岛市场，覆盖旅游海岸与本地居住区。',
  'ตลาดเกาะครอบคลุมชายฝั่งท่องเที่ยวและพื้นที่อยู่อาศัย',
  3
),
(
  'chiang-mai', 'Chiang Mai', '清迈', 'เชียงใหม่',
  'Chiang Mai Property | GoThailandHome',
  '清迈房产 | GoThailandHome',
  'อสังหาริมทรัพย์เชียงใหม่ | GoThailandHome',
  'Chiang Mai property pages for northern Thailand condominium and home inventory.',
  '清迈房产页面，覆盖泰国北部公寓与住宅库存（真实导入）。',
  'หน้าอสังหาฯ เชียงใหม่สำหรับคอนโดและที่อยู่อาศัยภาคเหนือ',
  'Northern Thailand’s largest city and lifestyle destination.',
  '泰国北部最大城市与生活方式目的地。',
  'เมืองใหญ่และจุดหมายไลฟ์สไตล์ของภาคเหนือ',
  4
),
(
  'rayong', 'Rayong', '罗勇', 'ระยอง',
  'Rayong Property | GoThailandHome',
  '罗勇房产 | GoThailandHome',
  'อสังหาริมทรัพย์ระยอง | GoThailandHome',
  'Rayong property hub for eastern industrial and coastal markets.',
  '罗勇房产中心，面向东部工业与沿海市场。',
  'ศูนย์อสังหาฯ ระยองสำหรับตลาดอุตสาหกรรมและชายฝั่งตะวันออก',
  'Eastern province with industrial and seaside housing demand.',
  '东部府治，兼具工业与海滨住房需求。',
  'จังหวัดตะวันออกที่มีความต้องการที่อยู่อาศัยแนวอุตสาหกรรมและชายทะเล',
  5
),
(
  'hua-hin', 'Hua Hin', '华欣', 'หัวหิน',
  'Hua Hin Property | GoThailandHome',
  '华欣房产 | GoThailandHome',
  'อสังหาริมทรัพย์หัวหิน | GoThailandHome',
  'Hua Hin property pages for resort-town projects and verified public listings.',
  '华欣房产页面，面向度假城镇项目与公开挂牌。',
  'หน้าอสังหาฯ หัวหินสำหรับโครงการเมืองตากอากาศและประกาศสาธารณะ',
  'Gulf resort town popular with weekenders and retirees.',
  '暹罗湾度假城镇，受周末客与退休客青睐。',
  'เมืองตากอากาศอ่าวไทยที่นิยมสำหรับวันหยุดและผู้เกษียณ',
  6
)
on conflict (slug) do update set
  name_en = excluded.name_en,
  name_zh = excluded.name_zh,
  name_th = excluded.name_th,
  seo_title_en = excluded.seo_title_en,
  seo_title_zh = excluded.seo_title_zh,
  seo_title_th = excluded.seo_title_th,
  seo_description_en = excluded.seo_description_en,
  seo_description_zh = excluded.seo_description_zh,
  seo_description_th = excluded.seo_description_th,
  summary_en = excluded.summary_en,
  summary_zh = excluded.summary_zh,
  summary_th = excluded.summary_th,
  sort_order = excluded.sort_order,
  is_active = true;

insert into public.districts (
  city_id, slug, name_en, name_zh, name_th,
  seo_title_en, seo_title_zh, seo_title_th,
  seo_description_en, seo_description_zh, seo_description_th,
  summary_en, summary_zh, summary_th, sort_order
)
select c.id, d.slug, d.name_en, d.name_zh, d.name_th,
  d.seo_title_en, d.seo_title_zh, d.seo_title_th,
  d.seo_description_en, d.seo_description_zh, d.seo_description_th,
  d.summary_en, d.summary_zh, d.summary_th, d.sort_order
from public.cities c
join (
  values
    ('bangkok', 'bang-kapi', 'Bang Kapi', '挽甲必', 'บางกะปิ',
      'Bang Kapi Bangkok Property | GoThailandHome',
      '曼谷挽甲必房产 | GoThailandHome',
      'อสังหาฯ บางกะปิ กรุงเทพฯ | GoThailandHome',
      'Bang Kapi district projects and verified public condo listings near Lam Sali and Ramkhamhaeng.',
      '挽甲必区域项目与公开公寓挂牌，靠近兰萨利与蓝康恒。',
      'โครงการและประกาศคอนโดย่านบางกะปิ ใกล้ลำสาลีและรามคำแหง',
      'Eastern Bangkok district around Ramkhamhaeng and Lam Sali interchange.',
      '曼谷东部区域，围绕蓝康恒与兰萨利换乘点。',
      'เขตกรุงเทพฯ ฝั่งตะวันออก ย่านรามคำแหงและแยกลำสาลี',
      1),
    ('bangkok', 'hua-mak', 'Hua Mak', '华目', 'หัวหมาก',
      'Hua Mak Bangkok Property | GoThailandHome',
      '曼谷华目房产 | GoThailandHome',
      'อสังหาฯ หัวหมาก กรุงเทพฯ | GoThailandHome',
      'Hua Mak neighbourhood property pages within Bang Kapi, Bangkok.',
      '华目社区房产页（曼谷挽甲必）。',
      'หน้าอสังหาฯ ย่านหัวหมาก ในเขตบางกะปิ กรุงเทพฯ',
      'Subdistrict of Bang Kapi on Ramkhamhaeng Road.',
      '挽甲必辖下华目，蓝康恒路一带。',
      'แขวงในเขตบางกะปิ ริมถนนรามคำแหง',
      2),
    ('pattaya', 'central-pattaya', 'Central Pattaya', '芭提雅中心', 'พัทยากลาง',
      'Central Pattaya Property | GoThailandHome',
      '芭提雅中心房产 | GoThailandHome',
      'อสังหาฯ พัทยากลาง | GoThailandHome',
      'Central Pattaya district pages for imported inventory.',
      '芭提雅中心区域页；库存随真实导入上线。',
      'หน้าย่านพัทยากลางสำหรับสินค้าที่นำเข้าจริง',
      'Core Pattaya beach and entertainment zone.',
      '芭提雅核心海滩与娱乐区。',
      'ย่านชายหาดและแหล่งบันเทิงหลักของพัทยา',
      1),
    ('phuket', 'kathu', 'Kathu', '卡图', 'กะทู้',
      'Kathu Phuket Property | GoThailandHome',
      '普吉卡图房产 | GoThailandHome',
      'อสังหาฯ กะทู้ ภูเก็ต | GoThailandHome',
      'Kathu district property hub on Phuket island.',
      '普吉岛卡图区房产中心页。',
      'ศูนย์อสังหาฯ อำเภอกะทู้ ภูเก็ต',
      'Inland Phuket district including Patong hillside areas.',
      '普吉内陆区，含芭东山麓一带。',
      'อำเภอตอนในของภูเก็ต รวมพื้นที่เชิงเขาป่าตอง',
      1),
    ('chiang-mai', 'mueang-chiang-mai', 'Mueang Chiang Mai', '清迈市区', 'เมืองเชียงใหม่',
      'Mueang Chiang Mai Property | GoThailandHome',
      '清迈市区房产 | GoThailandHome',
      'อสังหาฯ เมืองเชียงใหม่ | GoThailandHome',
      'Mueang Chiang Mai district property pages.',
      '清迈市区房产页。',
      'หน้าอสังหาฯ อำเภอเมืองเชียงใหม่',
      'Provincial capital district of Chiang Mai.',
      '清迈府府治所在区。',
      'อำเภอเมืองของจังหวัดเชียงใหม่',
      1),
    ('rayong', 'mueang-rayong', 'Mueang Rayong', '罗勇市区', 'เมืองระยอง',
      'Mueang Rayong Property | GoThailandHome',
      '罗勇市区房产 | GoThailandHome',
      'อสังหาฯ เมืองระยอง | GoThailandHome',
      'Mueang Rayong district property pages.',
      '罗勇市区房产页。',
      'หน้าอสังหาฯ อำเภอเมืองระยอง',
      'Provincial capital district of Rayong.',
      '罗勇府府治所在区。',
      'อำเภอเมืองของจังหวัดระยอง',
      1),
    ('hua-hin', 'hua-hin-town', 'Hua Hin', '华欣镇', 'หัวหิน',
      'Hua Hin Town Property | GoThailandHome',
      '华欣镇房产 | GoThailandHome',
      'อสังหาฯ หัวหิน | GoThailandHome',
      'Hua Hin town property pages on the Gulf of Thailand.',
      '暹罗湾华欣镇房产页。',
      'หน้าอสังหาฯ หัวหิน อ่าวไทย',
      'Core Hua Hin resort municipality.',
      '华欣核心度假市镇。',
      'เขตเทศบาลหัวหินหลัก',
      1)
) as d(
  city_slug, slug, name_en, name_zh, name_th,
  seo_title_en, seo_title_zh, seo_title_th,
  seo_description_en, seo_description_zh, seo_description_th,
  summary_en, summary_zh, summary_th, sort_order
)
on c.slug = d.city_slug
on conflict (slug) do update set
  city_id = excluded.city_id,
  name_en = excluded.name_en,
  name_zh = excluded.name_zh,
  name_th = excluded.name_th,
  seo_title_en = excluded.seo_title_en,
  seo_title_zh = excluded.seo_title_zh,
  seo_title_th = excluded.seo_title_th,
  seo_description_en = excluded.seo_description_en,
  seo_description_zh = excluded.seo_description_zh,
  seo_description_th = excluded.seo_description_th,
  summary_en = excluded.summary_en,
  summary_zh = excluded.summary_zh,
  summary_th = excluded.summary_th,
  sort_order = excluded.sort_order,
  is_active = true;
