-- STAGING ONLY
-- DO NOT APPLY TO PRODUCTION
-- Milestone: STAGING_DB_COMMIT_IMPLEMENTATION_V1
-- Requires: --confirm-staging + STAGING_PROJECT_REF isolation checks

CREATE TABLE IF NOT EXISTS staging_developers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  import_session_id TEXT NOT NULL REFERENCES staging_import_sessions(import_session_id),
  source_batch_id TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  source_schema TEXT NOT NULL,
  entity_status TEXT NOT NULL,
  review_state TEXT NOT NULL,
  confidence TEXT NOT NULL,
  evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  normalized_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_hash TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  candidate_id TEXT NOT NULL CHECK (candidate_id <> 'dev-unknown'),
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  aliases_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  official_website TEXT,
  official_website_verified BOOLEAN NOT NULL DEFAULT FALSE,
  identity_status TEXT NOT NULL,
  resolution_method TEXT,
  dns_status TEXT,
  duplicate_group_id TEXT,
  canonical_developer_id TEXT,
  reviewer_notes TEXT
);

CREATE TABLE IF NOT EXISTS staging_projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  import_session_id TEXT NOT NULL REFERENCES staging_import_sessions(import_session_id),
  source_batch_id TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  source_schema TEXT NOT NULL,
  entity_status TEXT NOT NULL,
  review_state TEXT NOT NULL,
  confidence TEXT NOT NULL,
  evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  normalized_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_hash TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  candidate_id TEXT NOT NULL,
  name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  slug_candidate TEXT,
  developer_candidate_id TEXT,
  canonical_developer_id TEXT,
  province TEXT,
  province_confidence TEXT NOT NULL,
  province_conflict BOOLEAN NOT NULL DEFAULT FALSE,
  location_json JSONB,
  project_status TEXT NOT NULL,
  duplicate_group_id TEXT,
  canonical_project_id TEXT,
  reviewer_notes TEXT
);

CREATE TABLE IF NOT EXISTS staging_assets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  import_session_id TEXT NOT NULL REFERENCES staging_import_sessions(import_session_id),
  source_batch_id TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  source_schema TEXT NOT NULL,
  entity_status TEXT NOT NULL,
  review_state TEXT NOT NULL,
  confidence TEXT NOT NULL,
  evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  normalized_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_hash TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  candidate_id TEXT NOT NULL,
  project_candidate_id TEXT,
  asset_type TEXT NOT NULL,
  original_filename TEXT,
  source_url TEXT,
  source_page TEXT,
  local_relative_path TEXT,
  sha256 TEXT NOT NULL,
  mime_type TEXT,
  width INT,
  height INT,
  file_size BIGINT,
  linkage_status TEXT,
  duplicate_group_id TEXT,
  storage_status TEXT NOT NULL DEFAULT 'PLANNED',
  storage_target_path TEXT,
  storage_object_id TEXT,
  reviewer_notes TEXT
);

CREATE TABLE IF NOT EXISTS staging_pdfs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  import_session_id TEXT NOT NULL REFERENCES staging_import_sessions(import_session_id),
  source_batch_id TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  source_schema TEXT NOT NULL,
  entity_status TEXT NOT NULL,
  review_state TEXT NOT NULL,
  confidence TEXT NOT NULL,
  evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  normalized_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_hash TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  candidate_id TEXT NOT NULL,
  project_candidate_id TEXT,
  category_candidate TEXT,
  original_filename TEXT,
  source_url TEXT,
  source_page TEXT,
  local_relative_path TEXT,
  sha256 TEXT NOT NULL,
  mime_type TEXT,
  page_count INT,
  file_size BIGINT,
  duplicate_group_id TEXT,
  storage_status TEXT NOT NULL DEFAULT 'PLANNED',
  storage_target_path TEXT,
  reviewer_notes TEXT
);

CREATE TABLE IF NOT EXISTS staging_news (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  import_session_id TEXT NOT NULL REFERENCES staging_import_sessions(import_session_id),
  source_batch_id TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  source_record_id TEXT NOT NULL,
  source_schema TEXT NOT NULL,
  entity_status TEXT NOT NULL,
  review_state TEXT NOT NULL CHECK (review_state <> 'PUBLISHED'),
  confidence TEXT NOT NULL,
  evidence_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  raw_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  normalized_payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_hash TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  candidate_id TEXT NOT NULL,
  title TEXT,
  normalized_title TEXT,
  source_url TEXT NOT NULL,
  source_domain TEXT,
  published_at TIMESTAMPTZ,
  captured_at TIMESTAMPTZ,
  freshness_status TEXT,
  developer_candidate_id TEXT,
  project_candidate_id TEXT,
  duplicate_group_id TEXT,
  reviewer_notes TEXT
);

CREATE TABLE IF NOT EXISTS staging_duplicate_candidates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  import_session_id TEXT NOT NULL REFERENCES staging_import_sessions(import_session_id),
  source_batch_id TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  matched_entity_id TEXT NOT NULL,
  match_kind TEXT NOT NULL,
  match_value TEXT NOT NULL,
  score NUMERIC,
  duplicate_group_id TEXT NOT NULL,
  review_state TEXT NOT NULL,
  evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_hash TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS staging_conflict_candidates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  import_session_id TEXT NOT NULL REFERENCES staging_import_sessions(import_session_id),
  source_batch_id TEXT NOT NULL,
  source_job_id TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  conflict_reason TEXT NOT NULL,
  severity TEXT NOT NULL,
  review_state TEXT NOT NULL CHECK (review_state = 'CONFLICT'),
  evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  content_hash TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);
