/**
 * First 50 Bangkok projects — real developments with official developer sources.
 * No fabricated prices/availability. Include coords only when already sourced (Livin).
 */
export const PROJECTS_W1 = [
  {
    slug: "the-livin-ramkhamhaeng",
    developer: "risland-thailand",
    district: "bang-kapi",
    en: "The Livin Ramkhamhaeng",
    zh: "The Livin 蓝康恒",
    th: "เดอะ ลิฟวิ่น รามคำแหง",
    website: "https://www.livinram.com/en",
    source: "https://www.livinram.com/en",
    lat: 13.763,
    lng: 100.647,
    transit: ["mrt", "mrt-yellow"],
  },
  {
    slug: "the-base-sukhumvit-77",
    developer: "sansiri",
    district: "suan-luang",
    en: "THE BASE Sukhumvit 77",
    zh: "THE BASE 素坤逸77",
    th: "เดอะ เบส สุขุมวิท 77",
    website: "https://www.sansiri.com/",
    source: "https://www.sansiri.com/",
  },
  {
    slug: "condo-u-sukhumvit-62-1",
    developer: "sansiri",
    district: "phra-khanong",
    en: "CONDO U Sukhumvit 62-1",
    zh: "CONDO U 素坤逸62-1",
    th: "คอนโด ยู สุขุมวิท 62-1",
    website: "https://www.sansiri.com/",
    source: "https://www.sansiri.com/",
  },
  {
    slug: "xt-huai-khwang",
    developer: "sansiri",
    district: "huai-khwang",
    en: "XT Huaikwang",
    zh: "XT 辉煌",
    th: "เอ็กซ์ที ห้วยขวาง",
    website: "https://www.sansiri.com/",
    source: "https://www.sansiri.com/",
    transit: ["mrt", "mrt-blue"],
  },
  {
    slug: "the-line-sukhumvit-101",
    developer: "sansiri",
    district: "phra-khanong",
    en: "THE LINE Sukhumvit 101",
    zh: "THE LINE 素坤逸101",
    th: "เดอะ ไลน์ สุขุมวิท 101",
    website: "https://www.sansiri.com/",
    source: "https://www.sansiri.com/",
    transit: ["bts"],
  },
  {
    slug: "xt-phayathai",
    developer: "sansiri",
    district: "ratchathewi",
    en: "XT Phayathai",
    zh: "XT 帕亚泰",
    th: "เอ็กซ์ที พญาไท",
    website: "https://www.sansiri.com/",
    source: "https://www.sansiri.com/",
    transit: ["bts", "arl"],
  },
  {
    slug: "rhythm-ekkamai",
    developer: "ap-thailand",
    district: "watthana",
    en: "Rhythm Ekkamai",
    zh: "Rhythm 埃卡迈",
    th: "ริทึ่ม เอกมัย",
    website: "https://www.apthai.com/",
    source: "https://www.apthai.com/",
    transit: ["bts"],
  },
  {
    slug: "life-asoke-rama-9",
    developer: "ap-thailand",
    district: "huai-khwang",
    en: "Life Asoke Rama 9",
    zh: "Life Asoke 拉玛九",
    th: "ไลฟ์ อโศก พระราม 9",
    website: "https://www.apthai.com/",
    source: "https://www.apthai.com/",
    transit: ["mrt", "mrt-blue"],
  },
  {
    slug: "life-ladprao",
    developer: "ap-thailand",
    district: "chatuchak",
    en: "Life Ladprao",
    zh: "Life 叻抛",
    th: "ไลฟ์ ลาดพร้าว",
    website: "https://www.apthai.com/",
    source: "https://www.apthai.com/",
    transit: ["bts"],
  },
  {
    slug: "life-one-wireless",
    developer: "ap-thailand",
    district: "pathum-wan",
    en: "Life One Wireless",
    zh: "Life One Wireless",
    th: "ไลฟ์ วัน ไวร์เลส",
    website: "https://www.apthai.com/",
    source: "https://www.apthai.com/",
    transit: ["bts"],
  },
  {
    slug: "aspire-sathorn-taksin",
    developer: "ap-thailand",
    district: "thon-buri",
    en: "Aspire Sathorn-Taksin",
    zh: "Aspire 沙吞-达信",
    th: "แอสปาย สาทร-ตากสิน",
    website: "https://www.apthai.com/",
    source: "https://www.apthai.com/",
    transit: ["bts"],
  },
  {
    slug: "the-room-sukhumvit-62",
    developer: "land-and-houses",
    district: "phra-khanong",
    en: "The Room Sukhumvit 62",
    zh: "The Room 素坤逸62",
    th: "เดอะ รูม สุขุมวิท 62",
    website: "https://www.lh.co.th/",
    source: "https://www.lh.co.th/",
    transit: ["bts"],
  },
  {
    slug: "the-room-sathorn-taksin",
    developer: "land-and-houses",
    district: "khlong-san",
    en: "The Room Sathorn-Taksin",
    zh: "The Room 沙吞-达信",
    th: "เดอะ รูม สาทร-ตากสิน",
    website: "https://www.lh.co.th/",
    source: "https://www.lh.co.th/",
    transit: ["bts"],
  },
  {
    slug: "the-tree-rio-bang-aor",
    developer: "pruksa-holding",
    district: "bang-phlat",
    en: "The Tree Rio Bang-Aor",
    zh: "The Tree Rio Bang-Aor",
    th: "เดอะทรี ริโอ้ บางอ้อ",
    website: "https://www.pruksa.com/",
    source: "https://www.pruksa.com/",
    transit: ["mrt"],
  },
  {
    slug: "chapter-one-shine-bang-pho",
    developer: "pruksa-holding",
    district: "bang-sue",
    en: "Chapter One Shine Bang Pho",
    zh: "Chapter One Shine Bang Pho",
    th: "แชปเตอร์วัน ชายน์ บางโพ",
    website: "https://www.pruksa.com/",
    source: "https://www.pruksa.com/",
    transit: ["mrt"],
  },
  {
    slug: "chapter-one-midtown-ladprao-24",
    developer: "pruksa-holding",
    district: "lat-phrao",
    en: "Chapter One Midtown Ladprao 24",
    zh: "Chapter One Midtown 叻抛24",
    th: "แชปเตอร์วัน มิดทาวน์ ลาดพร้าว 24",
    website: "https://www.pruksa.com/",
    source: "https://www.pruksa.com/",
  },
  {
    slug: "the-privacy-rama-9",
    developer: "pruksa-holding",
    district: "suan-luang",
    en: "The Privacy Rama 9",
    zh: "The Privacy 拉玛九",
    th: "เดอะ ไพรเวซี่ พระราม 9",
    website: "https://www.pruksa.com/",
    source: "https://www.pruksa.com/",
  },
  {
    slug: "knightbridge-collage-ramkhamhaeng",
    developer: "origin-property",
    district: "bang-kapi",
    en: "KnightBridge Collage Ramkhamhaeng",
    zh: "KnightBridge Collage 蓝康恒",
    th: "ไนท์บริดจ์ คอลลาจ รามคำแหง",
    website: "https://www.origin.co.th/",
    source: "https://www.origin.co.th/",
  },
  {
    slug: "origin-plug-play-sukhumvit-101",
    developer: "origin-property",
    district: "phra-khanong",
    en: "Origin Plug & Play Sukhumvit 101",
    zh: "Origin Plug & Play 素坤逸101",
    th: "ออริจิ้น ปลั๊ก แอนด์ เพลย์ สุขุมวิท 101",
    website: "https://www.origin.co.th/",
    source: "https://www.origin.co.th/",
    transit: ["bts"],
  },
  {
    slug: "knightsbridge-prime-sathorn",
    developer: "origin-property",
    district: "yan-nawa",
    en: "Knightsbridge Prime Sathorn",
    zh: "Knightsbridge Prime 沙吞",
    th: "ไนท์บริดจ์ ไพร์ม สาทร",
    website: "https://www.origin.co.th/",
    source: "https://www.origin.co.th/",
    transit: ["bts"],
  },
  {
    slug: "ideo-mobi-sukhumvit-66",
    developer: "ananda-development",
    district: "phra-khanong",
    en: "IDEO MOBI Sukhumvit 66",
    zh: "IDEO MOBI 素坤逸66",
    th: "ไอดีโอ โมบิ สุขุมวิท 66",
    website: "https://www.ananda.co.th/",
    source: "https://www.ananda.co.th/",
    transit: ["bts"],
  },
  {
    slug: "ideo-q-sukhumvit-36",
    developer: "ananda-development",
    district: "khlong-toei",
    en: "IDEO Q Sukhumvit 36",
    zh: "IDEO Q 素坤逸36",
    th: "ไอดีโอ คิว สุขุมวิท 36",
    website: "https://www.ananda.co.th/",
    source: "https://www.ananda.co.th/",
    transit: ["bts"],
  },
  {
    slug: "ashton-asoke",
    developer: "ananda-development",
    district: "watthana",
    en: "Ashton Asoke",
    zh: "Ashton Asoke",
    th: "แอชตัน อโศก",
    website: "https://www.ananda.co.th/",
    source: "https://www.ananda.co.th/",
    transit: ["bts", "mrt"],
  },
  {
    slug: "ideo-rama-9",
    developer: "ananda-development",
    district: "huai-khwang",
    en: "IDEO Rama 9",
    zh: "IDEO 拉玛九",
    th: "ไอดีโอ พระราม 9",
    website: "https://www.ananda.co.th/",
    source: "https://www.ananda.co.th/",
    transit: ["mrt"],
  },
  {
    slug: "supalai-oriental-sukhumvit-39",
    developer: "supalai",
    district: "watthana",
    en: "Supalai Oriental Sukhumvit 39",
    zh: "苏帕莱东方 素坤逸39",
    th: "ศุภาลัย โอเรียนทัล สุขุมวิท 39",
    website: "https://www.supalai.com/",
    source: "https://www.supalai.com/",
    transit: ["bts"],
  },
  {
    slug: "supalai-veranda-rama-9",
    developer: "supalai",
    district: "huai-khwang",
    en: "Supalai Veranda Rama 9",
    zh: "苏帕莱 Veranda 拉玛九",
    th: "ศุภาลัย เวอเรนด้า พระราม 9",
    website: "https://www.supalai.com/",
    source: "https://www.supalai.com/",
    transit: ["mrt"],
  },
  {
    slug: "supalai-elite-phayathai",
    developer: "supalai",
    district: "ratchathewi",
    en: "Supalai Elite Phayathai",
    zh: "苏帕莱 Elite 帕亚泰",
    th: "ศุภาลัย เอลีท พญาไท",
    website: "https://www.supalai.com/",
    source: "https://www.supalai.com/",
    transit: ["bts", "arl"],
  },
  {
    slug: "supalai-lite-sathorn-charoenrat",
    developer: "supalai",
    district: "yan-nawa",
    en: "Supalai Lite Sathorn-Charoenrat",
    zh: "苏帕莱 Lite 沙吞",
    th: "ศุภาลัย ไลท์ สาทร-เจริญราษฎร์",
    website: "https://www.supalai.com/",
    source: "https://www.supalai.com/",
  },
  {
    slug: "the-esse-sukhumvit-36",
    developer: "sc-asset",
    district: "khlong-toei",
    en: "The Esse Sukhumvit 36",
    zh: "The Esse 素坤逸36",
    th: "ดิ เอสส์ สุขุมวิท 36",
    website: "https://www.scasset.com/",
    source: "https://www.scasset.com/",
    transit: ["bts"],
  },
  {
    slug: "the-esse-asoke",
    developer: "sc-asset",
    district: "watthana",
    en: "The Esse Asoke",
    zh: "The Esse Asoke",
    th: "ดิ เอสส์ อโศก",
    website: "https://www.scasset.com/",
    source: "https://www.scasset.com/",
    transit: ["bts", "mrt"],
  },
  {
    slug: "vyva-thonglor",
    developer: "sc-asset",
    district: "watthana",
    en: "VYVA Thonglor",
    zh: "VYVA Thonglor",
    th: "วายวา ทองหล่อ",
    website: "https://www.scasset.com/",
    source: "https://www.scasset.com/",
    transit: ["bts"],
  },
  {
    slug: "lumpini-ville-phahol-saphanmai",
    developer: "lpn-development",
    district: "bang-khen",
    en: "Lumpini Ville Phahol-Saphanmai",
    zh: "Lumpini Ville 拍浩-萨潘迈",
    th: "ลุมพินี วิลล์ พหลฯ-สะพานใหม่",
    website: "https://www.lpn.co.th/",
    source: "https://www.lpn.co.th/",
    transit: ["bts"],
  },
  {
    slug: "casa-condo-asoke-dindaeng",
    developer: "quality-houses",
    district: "din-daeng",
    en: "Casa Condo Asoke-Dindaeng",
    zh: "Casa Condo Asoke-Dindaeng",
    th: "คาซ่า คอนโด อโศก-ดินแดง",
    website: "https://www.qh.co.th/",
    source: "https://www.qh.co.th/",
    transit: ["mrt"],
  },
  {
    slug: "ascott-embassy-sathorn",
    developer: "capitaland-thailand",
    district: "sathon",
    en: "Ascott Embassy Sathorn Bangkok",
    zh: "雅诗阁使馆沙吞曼谷",
    th: "แอสคอตต์ เอ็มบาสซี สาทร กรุงเทพฯ",
    website: "https://www.capitaland.com/th/en.html",
    source: "https://www.capitaland.com/th/en.html",
    transit: ["bts"],
  },
  {
    slug: "maestro-03-ratchada-rama-9",
    developer: "major-development",
    district: "huai-khwang",
    en: "Maestro 03 Ratchada-Rama 9",
    zh: "Maestro 03 拉差达-拉玛九",
    th: "มาเอสโตร 03 รัชดาฯ-พระราม 9",
    website: "https://www.major.co.th/",
    source: "https://www.major.co.th/",
    transit: ["mrt"],
  },
  {
    slug: "m-jive-sathorn-lumphini",
    developer: "major-development",
    district: "sathon",
    en: "M Jive Sathorn-Lumphini",
    zh: "M Jive 沙吞-伦披尼",
    th: "เอ็ม ไจฟ์ สาทร-ลุมพินี",
    website: "https://www.major.co.th/",
    source: "https://www.major.co.th/",
    transit: ["bts", "mrt"],
  },
  {
    slug: "m-silom",
    developer: "major-development",
    district: "bang-rak",
    en: "M Silom",
    zh: "M 是隆",
    th: "เอ็ม สีลม",
    website: "https://www.major.co.th/",
    source: "https://www.major.co.th/",
    transit: ["bts"],
  },
  {
    slug: "the-forestias",
    developer: "mqdc",
    district: "bang-na",
    en: "The Forestias",
    zh: "The Forestias",
    th: "เดอะ ฟอเรสเทียส์",
    website: "https://www.theforestias.com/",
    source: "https://www.theforestias.com/",
  },
  {
    slug: "whizdom-essence",
    developer: "mqdc",
    district: "phra-khanong",
    en: "Whizdom Essence Sukhumvit",
    zh: "Whizdom Essence",
    th: "วิซดอม เอสเซนส์",
    website: "https://www.mqdc.com/",
    source: "https://www.mqdc.com/",
    transit: ["bts"],
  },
  {
    slug: "modiz-rhyme-ramkhamhaeng",
    developer: "assetwise",
    district: "bang-kapi",
    en: "Modiz Rhyme Ramkhamhaeng",
    zh: "Modiz Rhyme 蓝康恒",
    th: "โมดิซ ไรย์ม รามคำแหง",
    website: "https://www.assetwise.co.th/",
    source: "https://www.assetwise.co.th/",
  },
  {
    slug: "kave-town-space",
    developer: "assetwise",
    district: "bang-khen",
    en: "Kave Town Space",
    zh: "Kave Town Space",
    th: "เคฟ ทาวน์ สเปซ",
    website: "https://www.assetwise.co.th/",
    source: "https://www.assetwise.co.th/",
  },
  {
    slug: "the-lofts-silom",
    developer: "raimon-land",
    district: "bang-rak",
    en: "The Lofts Silom",
    zh: "The Lofts 是隆",
    th: "เดอะ ลอฟท์ สีลม",
    website: "https://www.raimonland.com/",
    source: "https://www.raimonland.com/",
    transit: ["bts"],
  },
  {
    slug: "168-sukhothai-residences",
    developer: "raimon-land",
    district: "dusit",
    en: "168 Sukhothai Residences",
    zh: "168 素可泰",
    th: "168 สุโขทัย เรสซิเดนเซส",
    website: "https://www.raimonland.com/",
    source: "https://www.raimonland.com/",
  },
  {
    slug: "noble-around-ari",
    developer: "noble-development",
    district: "phaya-thai",
    en: "Noble Around Ari",
    zh: "Noble Around 阿里",
    th: "โนเบิล อราวน์ อารีย์",
    website: "https://www.noblehome.com/",
    source: "https://www.noblehome.com/",
    transit: ["bts"],
  },
  {
    slug: "noble-revolve-ratchada",
    developer: "noble-development",
    district: "huai-khwang",
    en: "Noble Revolve Ratchada",
    zh: "Noble Revolve 拉差达",
    th: "โนเบิล รีวอลฟ์ รัชดา",
    website: "https://www.noblehome.com/",
    source: "https://www.noblehome.com/",
    transit: ["mrt"],
  },
  {
    slug: "noble-beat",
    developer: "noble-development",
    district: "watthana",
    en: "Noble BEAT",
    zh: "Noble BEAT",
    th: "โนเบิล บีท",
    website: "https://www.noblehome.com/",
    source: "https://www.noblehome.com/",
    transit: ["bts"],
  },
  {
    slug: "samyan-mitrtown",
    developer: "frasers-property-thailand",
    district: "pathum-wan",
    en: "Samyan Mitrtown",
    zh: "三岩 Mitrtown",
    th: "สามย่าน มิตรทาวน์",
    website: "https://www.samyanmitrtown.com/",
    source: "https://www.samyanmitrtown.com/",
    transit: ["mrt", "mrt-blue"],
  },
  {
    slug: "one-bangkok",
    developer: "frasers-property-thailand",
    district: "pathum-wan",
    en: "One Bangkok",
    zh: "One Bangkok",
    th: "วัน แบงค็อก",
    website: "https://www.onebangkok.com/",
    source: "https://www.onebangkok.com/",
    transit: ["bts", "mrt"],
  },
  {
    slug: "singha-complex",
    developer: "singha-estate",
    district: "huai-khwang",
    en: "Singha Complex",
    zh: "胜者综合体",
    th: "สิงห์ คอมเพล็กซ์",
    website: "https://www.singhaestate.co.th/",
    source: "https://www.singhaestate.co.th/",
    transit: ["mrt", "mrt-blue"],
  },
  {
    slug: "niche-pride-thonglor-phetchaburi",
    developer: "sena-development",
    district: "watthana",
    en: "Niche Pride Thonglor-Phetchaburi",
    zh: "Niche Pride Thonglor",
    th: "นิช ไพรด์ ทองหล่อ-เพชรบุรี",
    website: "https://www.sena.co.th/",
    source: "https://www.sena.co.th/",
    transit: ["bts"],
  },
];
